# Generated by Django 2.2.15 on 2020-08-14 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unknow', max_length=100)),
                ('srcImg', models.URLField(blank=True, default='')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('star', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('freeServices', models.TextField()),
                ('services', models.TextField()),
                ('isSale', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unknow', max_length=100)),
                ('srcImg', models.URLField(blank=True, default='')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('freeServices', models.TextField()),
                ('capacity', models.TextField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Hotel')),
            ],
        ),
    ]
