# Generated by Django 2.2.15 on 2021-01-20 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameCustomer', models.CharField(default='Unknow', max_length=100)),
                ('phoneNumber', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('checkInDate', models.DateField()),
                ('checkOutDate', models.DateField()),
                ('numberAdult', models.IntegerField(default=0)),
                ('numberChildren', models.IntegerField(default=0)),
                ('numberBaby', models.IntegerField(default=0)),
                ('note', models.TextField()),
                ('status', models.CharField(default='New', max_length=10)),
                ('bookingDate', models.DateField()),
            ],
            options={
                'ordering': ['bookingDate'],
            },
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['numberBookings', 'id']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['numberBookings', 'id']},
        ),
        migrations.AddField(
            model_name='hotel',
            name='numberBookings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='numberBookings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='app.Hotel'),
        ),
    ]
