# Generated by Django 2.2.15 on 2021-01-21 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210121_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkInDate',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkOutDate',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
