# Generated by Django 2.2.15 on 2021-01-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210121_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
