# Generated by Django 2.2.15 on 2021-01-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='srcDetailImgs',
            field=models.TextField(default=''),
        ),
    ]
