# Generated by Django 2.2.15 on 2021-01-30 07:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_hotel_srcdetailimgs'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTimeline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='New', max_length=20)),
                ('modifiedDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('admin', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bookingTimelines', to='app.Admin')),
                ('booking', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bookingTimelines', to='app.Booking')),
            ],
            options={
                'ordering': ['-modifiedDate'],
            },
        ),
    ]
