# Generated by Django 2.2.15 on 2021-02-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_bookingtimeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtimeline',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
