# Generated by Django 2.2.15 on 2021-02-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_bookingtimeline_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
    ]
